### ISSUE TITLE
안녕하세요 프로그래머스 합승택시요금 최소거리 갱신할 때 반복문부분 질문이있어서 글남깁니다.

### ISSUE THREAD

**Issue by gkalstn000** [yuneg11/Programmers-Solutions#1]
다익스트라 알고리즘에서 초기값 설정해주고 본격적으로 MST거리 갱신하는 과정에서
`for k, i, j in product(range(n), repeat=3):`
여기서 k, i, j를
`for i, j, k in product(range(n), repeat=3):`
이렇게 바꾸면 답이 틀리는 경우가 생기더라구요.
문맥상으로 D[i][j] 를 갱신시키는 코드이니 (i, j)를 박아놓고 경유하는 노드를 바꿔가뭐 최솟값을 갱신하는게 맞다고 생각해지만 그게 틀리더라고요...; 혹시 왜 순서를 바꾸면 답이 틀려지는지 반례라던가 설명좀 부탁드려도될까요?

**Comment by yuneg11** [comment]
일단 해당 코드가 다익스트라 알고리즘이라고 잘못 생각하신 것 같습니다.
해당 코드는 [플로이드-워셜 알고리즘](https://ko.wikipedia.org/wiki/플로이드-워셜_알고리즘)입니다.

보통 다익스트라 알고리즘은 하나의 소스 노드에서 다른 타겟 노드까지의 거리를 구하는 1:1 또는 1:N의 상황에서 많이 쓰인다는 것을 알고 계실겁니다.
하지만 해당 문제에서는 소스 노드가 하나로 고정되어 있지 않기 때문에 모든 소스 노드에서 다른 모든 타겟 노드까지의 거리를 알아야 하는 N:N 상황이므로 다익스트라 알고리즘을 적용하려면 각각의 노드 N개에 대해서 다익스트라 알고리즘을 적용해야 합니다.
따라서 해당 문제는 N:N 거리를 바로 구할 수 있는 플로이드-워셜 알고리즘이 구현상 더 간단하여 선택하게 되었습니다.

k가 맨 앞에 나와야 하는 이유는 DP(동적계획법)과도 관계 있습니다.
하지만 제가 지금 설명하는 것보다 구글에서 플로이드-워셜 알고리즘의 작동과정을 찾아보시면 아마 이해하실 수 있을 것 같습니다.
이후에도 잘 모르시는 부분이 있으시면 추가로 말씀해 주세요.

**Comment by gkalstn000** [comment]
답변 감사합니다. 제가 다익스트라, 플로이드워셜알고리즘 둘다 잘 모르는 상태였네요. 2개다시 공부하고 이해가안되면 질문 드리겠습니다. 감사합니다!
