### ISSUE TITLE
프로그래머스 위클리챌린지 3, 4 주차 문제 해설

### ISSUE THREAD

**Issue by hanliang38** [yuneg11/Programmers-Solutions#2]
안녕하세요!
매번 프로그래머스 위클리문제를 풀 때마다 숏코딩으로 엄청 짧은 코드로 코테를 통과하셔서
보다가 숏코딩에 대한 풀이 법이 궁금해서 이슈 남깁니다!
3주차와 4주차 문제와 해설이 궁금해요!

또 어떻게 그렇게 짧은 코드로 풀이가 가능한건지, 알고 싶습니다!

**Comment by yuneg11** [comment]
안녕하세요
답변이 너무 늦어져서 죄송합니다.
이미 해결 하셨을 수도 있겠네요.
제가 최근까지 ICLR 2022 학회 기간이었던지라 많이 바빴습니다.

시간 관계상 3주차 문제는 아직은 풀 생각이 없습니다.
혹시라도 나중에 풀게되면 여기에도 업데이트 하겠습니다.
4주차 문제는 아마 이번주 안에 시간이 나면 그동안 풀었던 문제들도 같이 업데이트 하면서 같이 풀이를 남기겠습니다.

숏코딩은 저도 자료들이 있나 찾아봤는데 딱히 좋은게 없는것 같더라고요.
그래서 그나마 추천 드리는 것은 [Baekjoon Online Judge](https://www.acmicpc.net) 사이트에서 문제를 풀고 `숏코딩` 탭에서 다른 사람들의 풀이를 살펴보는 것입니다.
여러 숏코딩 풀이를 보다 보면 그동안 미쳐 생각하지 못했던 트릭이나 알고리즘 등을 찾아보실 수 있을 것 같습니다.
하지만 코드를 이상하게 꼬아서 푸는 종류의 숏코딩은 그다지 추천드리진 않습니다.
차라리 간단하게 풀었던 문제라도 몇 번씩 다시 생각해보면서 진짜 필요한 부분이 어떤 부분인지, 귀찮다고 대충 때우고 넘어간 부분은 없는지를 고민해보고 최소한으로 필요한 코드가 무엇일지를 분석하다보면 간단한 코드를 만들어 내는 능력이 생깁니다.

한낱 연구용 코드만 만들고 있는 제가 현업에 계신분께 이상한 소리만 한 것 같은데 적당히 걸러서 보시면 될 것 같습니다.
풀이가 업데이트 되면 여기에도 업데이트를 하겠습니다.

+)
답변을 달아놓고 확인해 보니 4주차 문제가 없어졌네요?
어떤 문제였는지 기억이 안나서 문제를 찾기 전까지는 풀이를 못 할 것 같습니다. 죄송합니다.
